config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rules

  resources :badges do
    member do
      delete :remove_image
    end
  end

  root 'tests#index'

  get :feedbacks, 'feedbacks/new'
  post :feedbacks, 'feedbacks/create'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index, shallow: true do
    member do
      post :start
    end
  end

  resources :passages, only: %i[show update] do
    member do
      get :result
      post :gist, to: 'admin/gists#create'
    end
  end

  namespace :admin do
    resources :categories
    resources :gists, only: :index
    resources :tests, shallow: true do
      patch :update_inline, on: :member
      resources :questions, except: :index do
        resources :answers, except: :index
      end
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord

  has_one :rule

  has_one_attached :image, dependent: :destroy
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: %i[ show edit update destroy ]

  # GET /badges or /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1 or /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges or /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to badge_url(@badge), notice: "Badge was successfully created." }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1 or /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to badge_url(@badge), notice: "Badge was successfully updated." }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1 or /badges/1.json
  def destroy
    @badge.destroy!

    respond_to do |format|
      format.html { redirect_to badges_url, notice: "Badge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def remove_image
    image = ActiveStorage::Attachment.find(params[:id])
    image.purge_later
    redirect_back(fallback_location: request.referer)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_badge
    @badge = Badge.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def badge_params
    params.require(:badge).permit(:title, :image)
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_badge.html.erb
<div  id="<%= dom_id badge %>">
  <div class="card bg-light mb-3 card--my">
    <div class="card-header d-flex">
      <%= badge.title %>
      <div class='ms-auto'>
        <%= link_to '', edit_badge_path(badge), class: 'btn btn-sm btn-primary bi bi-pen btn--small' %>
        <%= link_to '', badge, data: { turbo_method: :delete}, class: 'btn btn-sm btn-danger bi bi-trash' %>
      </div>
    </div>
    <div class="card-body">
      <% if badge.image.attached? %>
        <%= image_tag(badge.image, class: 'card-img-top', style: "object-fit: cover") %>
      <% end %>
    </div>
  </div>
</div>

app/views/badges/_form.html.erb
<div class='d-flex flex-column'>
  <%= form_with(model: badge) do |form| %>
    <%= render 'errors', resource: badge %>
    <div class="mb-3">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <% if badge.image.attached? %>
        <%= form.hidden_field :image, multiple: false, value: badge.image.signed_id %>
        <div class='d-flex gap-2 align-items-start'>
          <%= image_tag(badge.image, height: 150) %>
          <%= button_to '', remove_image_badge_path(badge), 
          data: { turbo_method: :delete }, class: 'btn btn-sm btn-danger bi bi-trash' %>
        </div>
      <% end %>
      <%= form.file_field :image, multiple: false, class: 'btn btn-primary my-3' %>
    </div>
    <div class="mb-3">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>
<%= render "form", badge: @badge %>
<br>
<div>
  <%= link_to "Back to badges", badges_path, class: 'btn' %>
</div>

app/views/badges/index.html.erb
<p>
  <%= link_to "New badge", new_badge_path, class: 'btn btn-primary' %>
</p>
<div id="badges" class='d-flex gap-3 flex-wrap'>
  <% @badges.each do |badge| %>
    <%= render badge %>
  <% end %>
</div>

app/views/badges/new.html.erb
<%= render "form", badge: @badge %>
<div>
  <%= link_to "Back to badges", badges_path %>
</div>

app/views/badges/show.html.erb
<%= render @badge %>