config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rules

  resources :badges do
    member do
      delete :remove_image
    end
  end

  root 'tests#index'

  get :feedbacks, 'feedbacks/new'
  post :feedbacks, 'feedbacks/create'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index, shallow: true do
    member do
      post :start
    end
  end

  resources :passages, only: %i[show update] do
    member do
      get :result
      post :gist, to: 'admin/gists#create'
    end
  end

  namespace :admin do
    resources :categories
    resources :gists, only: :index
    resources :tests, shallow: true do
      patch :update_inline, on: :member
      resources :questions, except: :index do
        resources :answers, except: :index
      end
    end
  end
end

app/models/passage.rb
# frozen_string_literal: true

class Passage < ApplicationRecord
  PASSAGE_MAX = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question

  def completed?
    current_question.nil?
  end

  def current_no
    test.questions.order(:id).where('id <= ?', current_question.id).count
  end

  def accept!(answers_ids)
    self.correct_questions += 1 if correct_answer?(answers_ids)
    save!
  end

  def grade
    100 * correct_questions / test.questions.count
  end

  def progress_width
    100.0 * current_no / test.questions.count
  end

  private

  def assign_first_question
    self.current_question = test.questions.first if test.present?
  end

  def assign_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_validation_set_question
    if new_record?
      assign_first_question
    else
      assign_next_question
    end
  end

  def correct_answer?(answer_ids)
    correct_count = correct_answers.count
    (correct_count == correct_answers.where(id: answer_ids).count) &&
      correct_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/passages_controller.rb
# frozen_string_literal: true

class PassagesController < ApplicationController
  before_action :set_test_passage

  def show; end

  def result; end

  def update
    @passage.accept!(params[:answer_ids])

    if @passage.completed?
      TestsMailer.completed_test(@passage).deliver_now
      redirect_to result_passage_path(@passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @passage = Passage.find(params[:id])
  end
end

app/views/passages/result.html.erb
<h2>
  <%= t('test_complete', test_title: @passage.test.title) %> 

</h2>
<% if @passage.grade >= Passage::PASSAGE_MAX %>
  <p style="color: green">
    <%= t('passed_test', result: @passage.grade) %>
  </p>
<% else %>
  <p style="color: red">
    <%= t('failed_test', result: @passage.grade) %>
  </p>
<% end %>

<%= link_to t('back_to_tests'), tests_path %>

app/views/passages/show.html.erb
<h1><%= @passage.test.title %></h1>
<div class="progress" role="progressbar" aria-label="Example 1px high" 
  aria-valuemin="0" aria-valuemax="100" style="height: 1px">
  <%= content_tag :div, '', class: 'progress-bar',
    data: { question_no: @passage.current_no,
    question_total: @passage.test.questions.count } %>
</div>
<b>
  <p>
    <%= Question.model_name.human %> #<%= @passage.current_no %>
    <%= t('.out_of') %>
    <%= @passage.test.questions.count %>
  </p>
  <%= @passage.current_question.body %>
</b>
<%= form_with url: passage_path(@passage), data: { turbo: false }, method: :put  do |form| %>
  <%= form.collection_check_boxes :answer_ids, @passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <div class='form-check'>
      <%= b.check_box id: "answers_ids_#{b.object.id}", class: 'form-check-input' %>
      <%= b.label class: 'form-check-label' %>
    </div>
  <% end %>
  <p> <%= form.submit t('.next'), class: 'btn btn-primary' %>
  </p>
<% end %>
<%= form_with url: gist_passage_path(@passage), data: { turbo: false } do |inside| %>
  <%= inside.submit t('.gist_question'), method: :post, class: 'btn btn-secondary' %>
<% end %>