config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rules

  resources :badges do
    member do
      delete :remove_image
    end
  end

  root 'tests#index'

  get :feedbacks, 'feedbacks/new'
  post :feedbacks, 'feedbacks/create'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index, shallow: true do
    member do
      post :start
    end
  end

  resources :passages, only: %i[show update] do
    member do
      get :result
      post :gist, to: 'admin/gists#create'
    end
  end

  namespace :admin do
    resources :categories
    resources :gists, only: :index
    resources :tests, shallow: true do
      patch :update_inline, on: :member
      resources :questions, except: :index do
        resources :answers, except: :index
      end
    end
  end
end

app/models/rule.rb
# frozen_string_literal: true

class Rule < ApplicationRecord
  belongs_to :badge, optional: true
  belongs_to :category, optional: true
  belongs_to :test, optional: true

  validates :title, presence: true, uniqueness: true

end

app/controllers/rules_controller.rb
# frozen_string_literal: true

class RulesController < ApplicationController
  before_action :set_rule, only: %i[show edit update destroy]

  # GET /rules or /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1 or /rules/1.json
  def show; end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit; end

  # POST /rules or /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to rule_url(@rule), notice: 'Rule was successfully created.' }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1 or /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to rule_url(@rule), notice: 'Rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1 or /rules/1.json
  def destroy
    @rule.destroy!

    respond_to do |format|
      format.html { redirect_to rules_url, notice: 'Rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_rule
    @rule = Rule.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def rule_params
    params.require(:rule).permit(:title, :status, :category_id, :test_id, :badge_id)
  end
end

app/helpers/rules_helper.rb
# frozen_string_literal: true

module RulesHelper
end

app/views/rules/_form.html.erb
<div class='input-group'>
  <%= form_with(model: rule) do |form| %>
    <%= render 'errors', resource: rule %>
    <div class="mb-3">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label :category_id %>
      <%= form.collection_select :category_id, Category.order(:title), :id, :title, { prompt: true }, { class: 'form-select' } %>
      <p><%= link_to "reset", '#' %></p>
    </div>
    <div class="mb-3">
      <%= form.label :test_id %>
      <%= form.collection_select :test_id, Test.order(:title), :id, :title, { prompt: true }, { class: 'form-select' } %>
    </div>
    <div class="mb-3">
      <%= form.label :badge_id %>
      <%= form.collection_select :badge_id, Badge.order(:title), :id, :title, { prompt: true }, { class: 'form-select' } %>
      <p><%= link_to "reset", '#' %></p>
    </div>
    <div class="mb-3">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/rules/_rule.html.erb
<div id="<%= dom_id rule %>" class="card text-bg-light mb-3">
  <div class="card-header d-flex">
    <%= rule.title %>
    <div  class='ms-auto'>
      <%= link_to '', edit_rule_path(rule), class: 'btn btn-primary bi bi-pen btn-sm' %>
      <%= link_to '', rule, data: { turbo_method: :delete}, class: 'btn btn-danger btn-sm bi bi-trash' %>
    </div>
  </div>
  <div class="card-body">
    <% if rule.category %>
      <h5 class="card-title"> Category: <%= rule.category.title %></h5>
    <% end %>
    <% if rule.test %>
      <h5 class="card-title"> Test: <%= rule.test.title %></h5>
    <% end %>
    <p class="card-text">
      <% if rule.badge %>
        <%= rule.badge.title %>
        <% if rule.badge.image.attached? %>
          <%= image_tag rule.badge.image, style: "width: 100%" %>
        <% end %>
      <% else %>
        no badge
      <% end %>
    </p>
  </div>
</div>

app/views/rules/edit.html.erb
<h1>Editing rule</h1>

<%= render 'form', rule: @rule %>

<br>

<div>
  <%= link_to 'Show this rule', @rule %> |
  <%= link_to 'Back to rules', rules_path %>
</div>

app/views/rules/index.html.erb
<%= link_to 'New rule', new_rule_path, class: 'btn btn-primary mb-3' %>
<div id="rules" class='d-flex gap-3 flex-wrap'>
  <% @rules.each do |rule| %>
    <%= render rule %>
  <% end %>
</div>

app/views/rules/new.html.erb
<h1>New rule</h1>

<%= render 'form', rule: @rule %>

<br>

<div>
  <%= link_to 'Back to rules', rules_path %>
</div>

app/views/rules/show.html.erb
<%= render @rule %>
<div>
  <%= link_to 'Edit this rule', edit_rule_path(@rule) %> |
  <%= link_to 'Back to rules', rules_path %>
  <%= button_to 'Destroy this rule', @rule, method: :delete %>
</div>