config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rules

  resources :badges do
    member do
      delete :remove_image
    end
  end

  root 'tests#index'

  get :feedbacks, 'feedbacks/new'
  post :feedbacks, 'feedbacks/create'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index, shallow: true do
    member do
      post :start
    end
  end

  resources :passages, only: %i[show update] do
    member do
      get :result
      post :gist, to: 'admin/gists#create'
    end
  end

  namespace :admin do
    resources :categories
    resources :gists, only: :index
    resources :tests, shallow: true do
      patch :update_inline, on: :member
      resources :questions, except: :index do
        resources :answers, except: :index
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :set_locale

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_tests_path
    else
      super
    end
  end

  def after_sign_out_path_for(_resource)
    new_user_session_path
  end

  def default_url_options
    { lang: I18n.locale == I18n.default_locale ? nil : I18n.default_locale }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end

  private

  def set_locale
    I18n.locale = I18n.locale_available?(params[:lang]) ? params[:lang] : I18n.default_locale
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to "https://github.com/#{author}/#{repo}", target: '_blank', rel: %w[nofollow noopener] do
      octicon "mark-github", class: 'my-icon'
    end
  end
end

app/views/application/_errors.html.erb
 <% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <%= t('.error', count: resource.errors.size) %>
    <ul>
      <% resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  <% end %>
<% end %>

app/views/application/_footer.html.erb
<footer class="footer">
  <div class="d-flex justify-content-between">
    <p>
      <%= current_year %> Учебный проект "Создание и прохождение тестов"
      в онлайн-школе
      <%= link_to 'Thinknetica', 
      'http://thinknetica.com', target: '_blank', rel: %w[nofollow noopener]
     %>
      <%= github_url('slydevruby', 'test-guru') %>
    </p>
    <p><%= link_to t(:feedback_link), feedbacks_new_path, class: 'btn btn-secondary' %></p>
  </div>
</footer>

app/views/application/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light bg-gradient mt-2 mb-4" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to root_path, class: 'btn btn-warning marg-right-2' do %>
      <i class="bi bi-rocket-takeoff"></i>
      Test
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user.is_a?(Admin) %>
          <li class="nav-item">
            <%= link_to admin_tests_path, class: 'nav-link active ml-4'  do %>
              <i class="bi bi-list-stars"></i>
              <%= t('.admin_panel') %>
            <% end %>
          </li>
          <li  class="nav-item">
            <%= link_to admin_categories_path, class: 'nav-link active' do %>
              <i class="bi bi-list-nested"></i>
              Categories
            <% end %>
          </li>
          <li  class="nav-item">
            <%= link_to rules_path, class: 'nav-link active' do %>
              <i class="bi bi-file-ruled"></i>
              Rules
            <% end %>
          </li>
          <li  class="nav-item">
            <%= link_to badges_path, class: 'nav-link active' do %>
              <i class="bi bi-award"></i>
              Badges
            <% end %>
          </li>
          <li  class="nav-item">
            <%= link_to t('.gist_panel'), admin_gists_path, class: 'nav-link active' %>
          </li>
        <% end %>
      </ul>
      <div class="d-flex" role="search">
        <% if user_signed_in? %>
          <ul class="navbar-nav align-items-center">
            <li  class="nav-item">
              <%= t('welcome', email: current_user.email) %>
            </li>
            <li class="nav-item">
              <%= link_to t('signout'), destroy_user_session_path, data: { turbo_method: :delete },class: 'nav-link active'  %>
            </li>
          </ul>
        <% else %>
          <ul class="navbar-nav">
            <%= link_to t('signin'), new_user_session_path, class: 'nav-link active' %>
            <%= link_to t('signup'), new_user_registration_path, class: 'nav-link active' %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>